defaults:
  - agent: mdp_prompt
  - override hydra/launcher: submitit_local

# unsupervised exploration
pretrained_data: sup
finetuned_data: val
pretrained_mask_type: random #[random,Currmask,Mixed-inv,Mixed-prog,...]
pretrained_mask_len: 1
pretrained_mask_ratio: 0.5
# task settings
task: walker_walk
discount: 0.99
# train settings
num_grad_steps: 300000
log_every_steps: 1000
# eval
eval_every_steps: 1000
num_eval_episodes: 10
# snapshot
snapshot_ts: 300000
snapshot_base_dir: /data/your_entity_hdd/currmask_data/output
# dataset
replay_buffer_dir: /data/your_entity_hdd/currmask_data
replay_buffer_size: 100000000
replay_buffer_num_workers: 16
batch_size: ${agent.batch_size}

# goal loader dataset
goal_buffer_dir: /data/your_entity_hdd/currmask_data
goal_buffer_size: 100000000
goal_buffer_num_workers: 4
# misc
seed: 2
device: cuda
save_video: true
use_tb: true
use_wandb: true
project: final_eval_prompt
notes: "your_entity"
mt: true
data_seed: 1
train_val_split: 0.8

hydra:
  run:
    dir: /data/ytang_hdd/maskdp_data/models/finetune/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}
